# vim:set ts=4 sw=4 expandtab:
formater:
    folder:
        format: '%(artist)s-%(album)s-%(date)s-AFRO'
        transformer: ['capwords', 'underscore', 'replace_list', 'remove_list', 'strip']
    metafiles:
        format: '00-%(artist)s-%(album)s-%(date)s'
        transformer: ['lowercase', 'underscore', 'replace_list', 'remove_list', 'strip']
    track:
        format: '%(tracknumber)02d-%(title)s'
        transformer: ['lowercase', 'underscore', 'replace_list', 'remove_list', 'strip']
    track_multicd:
        format: '%(discnumber)01d%(tracknumber)02d-%(title)s'
        transformer: ['lowercase', 'underscore', 'replace_list', 'remove_list', 'strip']
formater_order:
    replace_list: 0
    remove_list: 0
    lowercase: 10
    capwords: 10
    strip: 20
    underscore: 30
transformer:
    replace_list: {
        'é': 'e', 'è': 'e', 'ê': 'e', 'à': 'a', 'â': 'a', 'î': 'i',
        'É': 'E', 'È': 'E', 'Ê': 'E', 'À': 'A', 'Â': 'A', 'Î': 'I',
        'ô': 'o', 'ó': 'o', 'ù': 'u', 'í': 'i', 'ï': 'i', 'ç': 'c', 
        'Ô': 'O', 'Ó': 'O', 'Ù': 'U', 'Í': 'I', 'Ï': 'I', 'Ç': 'C',
        'œ': 'oe', 'æ': 'ae', '*': '_', '-': '_', '/': '-',
        '&' : 'and'
    }
    remove_list: ['!', '.', ',', '?', ':', '#', '"']
playlist:
    m3u:
        extension: 'm3u'
        save_on_append: true
hasher:
    list: ['sfv', 'shasum']
    save_on_perform: true
    sfv:
        extension: 'sfv'
    shasum:
        extension: 'sha512sum'
        algorithm: 'sha512'  
tools:
    encoder:
        need_input_remove: true
    ripper:
        binary: 'cdparanoia'
        format: '%(binary)s %(options)s %(tracknumber)d %(outfile)s'
        options: '-w -z'

